# Generated by Django 6.0.2 on 2026-05-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название промпта')),
                ('role', models.CharField(choices=[('extractor', 'Экстрактор (Извлечение)'), ('interpreter', 'Интерпретатор (Анализ)'), ('verifier', 'Верификатор (Проверка)')], max_length=20, unique=True)),
                ('system_prompt', models.TextField(verbose_name='Системный промпт')),
                ('context_data', models.TextField(blank=True, null=True, verbose_name='Дополнительный контекст/Примеры')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
