# Generated by Django 6.0.2 on 2026-05-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompttemplate',
            options={'verbose_name': 'Шаблон промпта', 'verbose_name_plural': 'Шаблоны промптов'},
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='context_data_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный контекст/Примеры'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='context_data_es',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный контекст/Примеры'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='context_data_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный контекст/Примеры'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='system_prompt_en',
            field=models.TextField(null=True, verbose_name='Системный промпт'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='system_prompt_es',
            field=models.TextField(null=True, verbose_name='Системный промпт'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='system_prompt_ru',
            field=models.TextField(null=True, verbose_name='Системный промпт'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название (для админки)'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='role',
            field=models.CharField(choices=[('extractor', 'Экстрактор (Извлечение)'), ('interpreter', 'Интерпретатор (Анализ)')], max_length=20, unique=True, verbose_name='Роль в пайплайне'),
        ),
    ]
