# Generated by Django 6.0.2 on 2026-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_prompttemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='role',
            field=models.CharField(choices=[('extractor', 'Экстрактор (Извлечение)'), ('interpreter', 'Интерпретатор (Анализ)'), ('chat_assistant', 'Чат-ассистент')], max_length=20, unique=True, verbose_name='Роль в пайплайне'),
        ),
    ]
