# Generated by Django 6.0.2 on 2026-02-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/faq/', verbose_name='Изображение'),
        ),
    ]
