# Generated by Django 6.0.2 on 2026-02-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_faqitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/blocks/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Уникальный ключ'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Внутреннее название (или Заголовок)'),
        ),
    ]
