# Generated by Django 6.0.2 on 2026-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contentblock_image_alter_contentblock_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='slug',
            field=models.CharField(choices=[('home_hero', 'Главный экран (О ПРОЕКТЕ)'), ('feature_1', 'Преимущество 1 (Динамика)'), ('feature_2', 'Преимущество 2 (Анализ)'), ('feature_3', 'Преимущество 3 (История)'), ('feature_4', 'Преимущество 4 (Риски)')], help_text='Выберите блок страницы, который хотите заполнить', max_length=100, unique=True, verbose_name='Уникальный ключ'),
        ),
    ]
