# Generated by Django 6.0.2 on 2026-02-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_contentblock_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, help_text='ВНИМАНИЕ: Загрузка изображения доступна ТОЛЬКО для блока "Главный экран (О ПРОЕКТЕ)"', null=True, upload_to='cms/blocks/', verbose_name='Изображение'),
        ),
    ]
