# Generated by Django 6.0.2 on 2026-02-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_legaldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqitem',
            name='image',
        ),
    ]
