# Generated by Django 6.0.2 on 2026-05-05 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_patientprofile_chronic_diseases_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('disease', 'Заболевание'), ('bad_habit', 'Вредная привычка'), ('good_habit', 'Полезная привычка'), ('feature', 'Особенность организма')], max_length=20, verbose_name='Категория')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Кастомная?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_traits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTraitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали (стаж, частота, дозировки)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_traits', to='core.patientprofile')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='premium.trait')),
            ],
            options={
                'unique_together': {('patient', 'trait')},
            },
        ),
    ]
