# Generated by Django 6.0.2 on 2026-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimize_tokens', models.BooleanField(default=True, verbose_name='Оптимизация токенов (JSON-диета и Суммаризация)')),
            ],
            options={
                'verbose_name': 'Настройки чата',
                'verbose_name_plural': 'Настройки чата',
            },
        ),
    ]
