# Generated by Django 6.0.2 on 2026-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_chatsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_summarized',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
