export function DisclaimerEn() {
  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-400 font-medium text-right mb-8">Last Updated: May 8, 2026</p>
      
      <div className="bg-red-50 border border-red-200 rounded-xl p-5 mb-8">
        <h3 className="text-red-800 font-bold text-lg mb-2">WARNING: THIS SERVICE IS NOT A DOCTOR</h3>
        <p className="text-red-700 font-medium">
          The webdoc.life platform and its artificial intelligence technologies do not provide medical advice, diagnoses, or treatment plans.
        </p>
      </div>

      <h3 className="text-lg font-bold mt-6 text-slate-800">1. Informational Purposes Only</h3>
      <p>All materials, test interpretations, charts, and text comments generated by the service are provided solely for informational and educational purposes. They are designed to help you better understand the structure of your medical documents but are no substitute for a professional medical opinion.</p>

      <h3 className="text-lg font-bold mt-6 text-slate-800">2. Potential AI and OCR Errors</h3>
      <p>We use Optical Character Recognition (OCR) and Large Language Models (LLM). These technologies are prone to errors (hallucinations). The AI might incorrectly recognize a number on a blurry photo or misinterpret a laboratory's reference range. You are responsible for cross-checking the service's output with your original laboratory report.</p>

      <h3 className="text-lg font-bold mt-6 text-slate-800">3. No Self-Medication</h3>
      <p>Never disregard professional medical advice or delay in seeking it because of something you have read on this website. Do not alter your medication dosages based on AI-generated reports.</p>

      <h3 className="text-lg font-bold mt-6 text-slate-800">4. Medical Emergencies</h3>
      <p>If you think you may have a medical emergency, call your doctor or emergency services immediately. The use of the webdoc.life service in emergency situations is strictly prohibited.</p>
    </div>
  );
}