# Generated by Django 6.0.2 on 2026-02-16 05:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientprofile_medicalanalysis_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField(blank=True, null=True)),
                ('string_value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atomic_indicators', to='core.medicalanalysis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='core.patientprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'slug', 'date'], name='core_analys_patient_f6488c_idx')],
            },
        ),
    ]
