# Generated by Django 6.0.2 on 2026-03-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analysisindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='Хронические заболевания', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Рост в см', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lifestyle',
            field=models.TextField(blank=True, help_text='Вредные привычки, диета, активность', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Вес в кг', null=True),
        ),
    ]
