# Generated by Django 6.0.2 on 2026-05-02 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patientprofile_chronic_diseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisindicator',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='analysisindicator',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='analysisindicator',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='analysisindicator',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='medicalanalysis',
            name='ai_result',
            field=models.JSONField(blank=True, null=True, verbose_name='Результат ИИ'),
        ),
        migrations.AlterField(
            model_name='medicalanalysis',
            name='file',
            field=models.FileField(upload_to='analyses/%Y/%m/%d/', verbose_name='Файл анализа'),
        ),
        migrations.AlterField(
            model_name='medicalanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В работе'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='Хронические заболевания', null=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Рост в см', null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='lifestyle',
            field=models.TextField(blank=True, help_text='Вредные привычки, диета, активность', null=True, verbose_name='Образ жизни'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Вес в кг', null=True, verbose_name='Вес'),
        ),
    ]
