# Generated by Django 6.0.2 on 2026-05-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_analysisindicator_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='chronic_diseases',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='lifestyle',
        ),
        migrations.AddField(
            model_name='medicalanalysis',
            name='parent_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reanalyses', to='core.medicalanalysis', verbose_name='Оригинальный анализ'),
        ),
        migrations.AlterField(
            model_name='medicalanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.patientprofile'),
        ),
    ]
