# Generated by Django 6.0.2 on 2026-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalanalysis',
            name='chat_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое содержание чата (Архив)'),
        ),
    ]
