# Generated by Django 6.0.2 on 2026-05-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_medicalanalysis_chat_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
            ],
            options={
                'verbose_name': '📈 Дашборд Аналитики',
                'verbose_name_plural': '📈 Дашборд Аналитики',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.medicalanalysis',),
        ),
    ]
