# Generated by Django 6.0.2 on 2026-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_systemanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PRO до'),
        ),
    ]
